//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace u23693313_HW03.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class DocumentArchive
    {
        public int ArchiveId { get; set; }
        public string ReportName { get; set; }

        [AllowHtml]
        public string Description { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public System.DateTime ArchivedDate { get; set; }
    }
}
